#!/bin/bash

# lock sreen

icon="/home/knary/pics/lock.png"
tmpbg='/tmp/sshot_tmp.png'

#import -window root "$tmpbg"
scrot -z "$tmpbg"

convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
rm /tmp/sshot_tmp.png
